### ISSUE TITLE
sex and weight_unit metadata values

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-etl#142]
# Statement of problem
The descriptions for the *sex* and *weight_unit* ingest metadata fields are incorrect.

The metadata fields are defined in the legacy field-*.yaml files. 

# Solution options
1. Correct in the legacy field-*.yaml files, which were supposed to be deprecated.
2. Add fields to the CEDAR templates.

**Comment by ngehlenborg** [comment]
@AlanSimmons Looks like there are other mouse specific descriptions for things that maybe should not be mouse specific (`date_of_death` -- although unlikely to appear in human context but still possible to apply to a different model organism). 

CC @bhonick @maxsibilla

**Comment by jpuerto-psc** [comment]
Fields have been adjusted in HuBMAP's IVT: https://github.com/hubmapconsortium/ingest-validation-tools/pull/1329

murine-source fields should be available via CEDAR, so this should not cause any conflicts on their end.
