### ISSUE TITLE
Synch organ list with Organs list in HRA

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-etl#153]

**Comment by AlanSimmons** [comment]
# HuBMAP
## change
 - Lymph Vasculature - from UBERON:001473 to UBERON:UBERON:0004536
## remove
 - Sternum
## add
 - Blood Vasculature
 - Pelvis
 - Mammary Gland (left, right)
 - Peripheral Nervous System
 ## question
 - Tonsil

# SenNet
## remove
 - Breast

**Comment by AlanSimmons** [comment]
Although UBERON now has codes for left and right ovary, we will stick with the FMA codes.

**Comment by shirey** [comment]
@yuanzhou None of these new organs should allow multiple instances to be added against the same Donor
@bherr2 or @AlanSimmons  Once those are added to UBKG let @BirdMachine (maybe create a new card) know which are available in the RUI so she can configure the Ingest UI for those that should show the "Register Location" button.

**Comment by AlanSimmons** [comment]
I'm not sure which of these organs are available in the RUI.
- This file has reference organs, but no RUI 2-letter codes: https://apps.humanatlas.io/api/v1/reference-organs
- This file has RUI codes, but I'm unsure of its currency: https://github.com/hubmapconsortium/hra-workflows-runner/blob/main/src/xconsortia/metadata.js#L6-L212

**Comment by bherr2** [comment]
Ok, I'm glad you brought it up. I don't know why people put that as "RUI code". Those are the two letter codes from hubmap that correspond to organs.

**Comment by AlanSimmons** [comment]
To my knowledge, SenNet does not use these RUI codes; instead, they key off of UBERON codes.

**Comment by bherr2** [comment]
Same

**Comment by lchoy** [comment]
> Ok, I'm glad you brought it up. I don't know why people put that as "RUI code". Those are the two letter codes from hubmap that correspond to organs.

Who defines the allocation and mapping of the two letter codes to ontology IDs such as UBERON?

**Comment by bherr2** [comment]
HuBMAP created the 2 letter organ codes initially (not sure who minted them originally in that group, you'll have to ask someone at IEC @shirey ?). We created 3D reference organs that were tagged via Uberon. We then needed to say what data from HuBMAP could be registered with what 3D reference organs. Thus the 2 letter organ code to Uberon term mapping was initially born.
