### ISSUE TITLE
Create new entity type "Publication"

### ISSUE THREAD

**Issue by maxsibilla** [x-atlas-consortia/ubkg-etl#42]
There is a new entity type that we would like to be added to the provenance called "Publication", which is a subclass of Dataset.

This entity type should be returned via this endpoint: https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000012&child_sabs=SENNET

**Comment by AlanSimmons** [comment]
@maxsibilla Do you mean a new dataset type of "publication", such as is currently available via this endpoint in HUBMAP?

https://ontology.api.hubmapconsortium.org/datasets?application_context=HUBMAP

```
{
"alt-names": [],
"contains-pii": false,
"data_type": "publication",
"dataset_provider": "HuBMAP IEC",
"description": "Publication Data",
"primary": false,
"vis-only": false,
"vitessce-hints": []
},
{
"alt-names": [],
"contains-pii": false,
"data_type": "publication_ancillary",
"dataset_provider": "HuBMAP IEC",
"description": "Publication Data [ancillary]",
"primary": "",
"vis-only": true,
"vitessce-hints": [
"json"
]
},
```

**Comment by maxsibilla** [comment]
@AlanSimmons we would like that as well, I was about to create another card for that endpoint. We still need a "publication" entity type though

**Comment by AlanSimmons** [comment]
@maxsibilla I have added the publication and publication ancillary datasets to SenNet.

The application ontology requires unique terms for concepts. "Publication" is currently the term for the Dataset Data Type code for the Publication dataset.  This means that the name of the Publication _entity_ has to be different. Right now, I have named it **Publication Entity**.

**Comment by AlanSimmons** [comment]
Changes published to prod.
