### ISSUE TITLE
Removing underscores from SABs

### ISSUE THREAD

**Issue by benstear** [x-atlas-consortia/ubkg-etl#46]
I'm also removing underscores from all SABs Ive ingested. This will eliminate the need for writing in exceptions in the `codeReplacements` function which currently replaces underscores with spaces:

**GTEX_EQTL** --> **GTEXEQTL**
**GTEX_EXP** --> **GTEXEXP**
**GTEX_COEXP** --> **GTEXCOEXP** 
**HPO_MP** --> **HPOMP** (human-mouse phenotype mappings)
**HCOP_MP** --> **HCOPMP**  (genotype-phenotype for mouse)
**HGNC_HPO** -- **HGNCHPO** (genotype-phenotype for human)

All of these, except for the GTEX_EQTL and GTEX_EXP, are relationship only SABs meaning they appear only as SABs on edges in the graph. The 2 GTEX SABs (GTEX_EQTL and GTEX_EXP) are code SABs so we'll need to make the same formatting changes (removing the underscore) from any set of assertions which use them. Luckily, I believe its just ERCC who is using GTEX_EQTL codes and I can send them an email today letting them know of the changes.

**Comment by benstear** [comment]
these changes have been made, we need to test that they don't cause any errors in the ingestion process or result in any unexpected behavior in the graph.

**Comment by AlanSimmons** [comment]
No errors in ingestion.
