### ISSUE TITLE
bug: old version of CCF ontology 

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-etl#56]
# Statement of problem
The latest version of the CCF (2.1.0) is at URL:
https://data.bioontology.org/ontologies/CCF/submissions/12/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb

The current version of the CCF in the ontologies.json file is 2.0.1, at URL:
https://data.bioontology.org/ontologies/CCF/submissions/11/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb

Note version 11 vs 12.

The old version does not contain a relationship that Jonathan needs for analysis.

# Solution
Generate new base context of UBKG, using the correct version of CCF.

**Comment by bherr2** [comment]
PS v2.2.0 will be out on Thursday!

**Comment by AlanSimmons** [comment]
That's fine. Jonathan is trying to do something on a deadline, and he assumed that the CCF data would include the located_in relation that's in 2.1 but not in the version that I was downloading. Either that, or there is another issue in our script that I have to debug. Once 2.2.0 is out, I can regenerate using that version, too.

**Comment by AlanSimmons** [comment]
@bherr2 Is there a chance that there is an issue with the OWL file that's published in BioPortal? I ask because our script extracts some of the relationships from the file, but not all. For example, it extracts the ct_is_a, ccf_part_of, and subclassOf, but none of the others--e.g., located_in.

**Comment by AlanSimmons** [comment]
I think that the problem is that the CCF OWL file is in OWL/XML format, not RDF/XML format. The conversion script uses rdflib, which does not parse OWL/XML by default. The owl file that the script saves out after downloading and parsing has all of the original owl tags stripped from it.

**Comment by AlanSimmons** [comment]
I'm not sure why this is the case, but 3 of the edges in the OWL file translate without a problem:

- http://purl.org/ccf/latest/ccf.owl#ct_is_a	
- http://purl.org/ccf/latest/ccf.owl#ccf_part_of	
- http://www.w3.org/2000/01/rdf-schema#subClassOf	

However, the other edges (e.g., ccf_located_in, ccf_ct_isa, etc.) do not translate to the relations file. 

I suspect that some of the edge information is available only in owl tags and is lost when rdflib.Graph.parse uses the 'xml' format, which results in a RDF/XML conversion.

I'm going to try the conversion recommended in [this discussion](https://github.com/RDFLib/rdflib/discussions/1571) of the rdflib github. If that doesn't work, I will work with the GZipped CSV stored in NCBO BioPortal.

**Comment by AlanSimmons** [comment]
False alarm! 

The actual error was a duplicate reference in one of the configuration files to an ancient version of the CCF (https://hubmapconsortium.github.io/hubmap-ontology/ccf.owl).

**Comment by AlanSimmons** [comment]
I have removed all duplicate references to CCF that were in the ontologies.json file. This included references to prior version of CCF and CCF-ASTCB.
