### ISSUE TITLE
Standardize code format to SAB:CODE

### ISSUE THREAD

**Issue by AlanSimmons** [x-atlas-consortia/ubkg-etl#70]
# Statement of problem
The generation script (OWL-UMLS-GRAPH) formats codes using the space character as delimiter--e.g., UBERON 99999.  The script also accommodates alternate code formatting from some ontologies, such as HGNC, GO, and PGO, in which the SAB is repeated to account for leading zeroes--e.g., HGNC HGNC:9999.

# Requested change
Standardize format of all code IDs to SAB:CODE.

**Comment by bherr2** [comment]
Yes, this would be ideal. That is how RDF technologies, ontologies, and other semantic web protocols format prefixes/[CURIEs](https://cthoyt.com/2021/09/14/curies.html).

**Comment by AlanSimmons** [comment]
This will entail changing the default formats for codes from HGNC, GO, and HP.  This would need to be done either as part of the initial extract of UMLS data or as a separate step performed prior to the first ingestion.

Codes from some sources are stored in nonstandard formats in the UMLS. For example, the code from HP for "Past Medical History" is stored as HPO HP:0032443. 

In addition,
HGNC codes are stored in format HGNC HGNC:x.
GO codes are stored in format GO GO:x.


![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/c1998c0c-3ecb-4462-9805-d1a297d3cb09)

**Comment by AlanSimmons** [comment]
The change also has downstream implications for: 

- UBKG API endpoints
- all ingestions that refer to codes from HGNC, HP, and GO

**Comment by AlanSimmons** [comment]
# Design decision
There are two points in the workflow in which codes from the UMLS can be standardized:

## Point 1: At extraction from the Neptune data warehouse--i.e., in the source framework script.

- Pros:
   1. The basic structure of the generation script can remain as it is.
   2. There is lower risk of forgetting to initialize UMLS data prior to generation of the base context.

-   Cons:
Loss of original form of extracted UMLS data.

 
## Point 2: Between extraction and import of the UMLS data to form the base context of UBKG.

- Pros:
   1. The original formatting of UMLS data is available.
   2. It is likely to be easier to format data using Python than SQL.

- Cons:
   1. It will require a separate, explicit step in the generation framework.
   2. There is a risk of forgetting the explicit step.


Because I think that it is important that we understand the original state of the UMLS content, I will standardize at the second point.

**Comment by AlanSimmons** [comment]
# Plan
1. Reformat UMLS CSVs to SAB CODE.
2. Reformat OWLNETS_UMLS_GRAPH to use colon as exclusive delimiter between SAB and CODE.
3. Validate that UMLS UBKG context both shows expected reformatting for HGNC etc. and shows CodeID as SAB:CODE instead of SAB CODE.
4. Modify representation of codes from HGNC, GO in custom data sources, including UNIPROTKB, HUBMAP, SENNET, and AZ.
5. Regression test for all SABs that refer to HGNC, GO, HPO, PGO, HCOP. Modify scripts accordingly.

**Comment by AlanSimmons** [comment]
Standardized the format for codes and codeIDs in UMLS CSVs.

HGO, GO, and HPO are all now in format SAB:CODE.

I did discover another non-compliant format: HCPCS Level codes, which are formatted by default like this:

`HCPCS Level n: Exxxx-Exxxx `

The format is now 
`HCPCS:Level_n_Exxxx-Exxxx`

**Comment by AlanSimmons** [comment]
# Results of regression testing: UMLS conversion

## Test
1. Run umls_init.py script on UMLS CSVs.
2. Import CSVs into UBKG instance.
3. Query UBKG.

## Result: 
1. HGNC, HPO, GO, and HCPCS Level codes are formatted as expected.
2. All CodeID formatted as _SAB_:_CODE_


## Example: HGNC, HPO, GO

`match (c:Code) where c.SAB='HPO' return c.SAB, c.CODE, c.CodeID limit 10`

![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/f6be9c71-f26c-48f8-b4e6-8502f1f53394)


## Example: HCPCS Level
`match (c:Code) where  c.CodeID STARTS WITH 'HCPCS:Level' AND c.SAB='HCPCS' return c.SAB, c.CODE, c.CodeID limit 5`


![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/783b0960-e2c9-432e-be58-5ef43215cc19)

**Comment by AlanSimmons** [comment]
# UBERON regression testing

Goals: 
1. The revised codeReplacements functionality correctly assumes that the delimiter between SAB and Code in CodeID is the colon.
2. OWLNETS_UMLS_GRAPH correctly maps codes to dbxrefs, both to codes and UMLS CUIs.

## Test
1. Ingest UBERON from OWLNETS files. 
2. Import CSVs into UBKG.
3. Query 

## Results: as expected.

## Examples

1. UBERON to UBERON edge. Both UBERON codes have dbxrefs to UMLS concepts.
`match(c1:Code),(c2:Code),p=shortestpath((c1)-[*0..3]-(c2)) WHERE c1.CodeID='UBERON:0004684' AND c2.CodeID='UBERON:0002275' RETURN p`

![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/1be6697d-2b69-4d7e-b527-dc36401aaf42)

2. GO to GO edge. Both GO codes have dbxrefs to UMLS concepts.
`match(c1:Code),(c2:Code),p=shortestpath((c1)-[*0..3]-(c2)) WHERE c1.CodeID='GO:0050671' AND c2.CodeID='GO:0046651' RETURN p`

![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/e4d02518-f7b0-415f-b5fa-364e471e19a5)

3. CL to CL edge. One CL code has a dbxref to a UMLS concept; the other has no dbxrefs.
`match(c1:Code),(c2:Code),p=shortestpath((c1)-[*0..3]-(c2)) WHERE c1.CodeID='CL:0000546' AND c2.CodeID='CL:0001051' RETURN p`

![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/346fdd6f-8714-49fc-804f-8de79f8eaa48)

4. CL to CL edge. One CL code has a dbxref to a non-UMLS code.
`match(c1:Code),(c2:Code),p=shortestpath((c1)-[*0..3]-(c2)) WHERE c1.CodeID='CL:0000020' AND c2.CodeID='CL:0000015' RETURN p`

![Image](https://github.com/x-atlas-consortia/ubkg-etl/assets/10928372/559a50d7-18c7-4492-8da6-08f6b7dd4cde)

CL:0000020 has a dbxref to FMA:72291, which has a dbxref to UMLS:C0037866.

**Comment by AlanSimmons** [comment]
# Base context converted
The SABs of the [base context ](https://ubkg.docs.xconsortia.org/contexts/#ubkg-base-context-umls-plus)have been converted to SAB:code.

This entailed changes to code in the suite of generation scripts as well as to the SimpleKnowledge spreadsheets.

**Comment by AlanSimmons** [comment]
# HuBMAP/SenNet context converted

The SABs of the [HuBMAP/SenNet context](https://ubkg.docs.xconsortia.org/contexts/#hubmapsennet-context) have been converted to SAB:code.
